### ISSUE TITLE
请问如何控制侧边栏收起的时间？

### ISSUE THREAD

**Issue by zires** [iview/iview-admin#1204]
有没有参数可以控制？

**Comment by tolking** [comment]
不是很懂你的问题
但通过 css 可以控制动画过度的时间
``` css
.ivu-layout-sider {
    transition: all 0.2s ease-in-out;
}
```
