### ISSUE TITLE
windows和ubuntu下sidebar如果展开的过多会出现滚动条

### ISSUE THREAD

**Issue by baifan** [iview/iview-admin#274]
windows和ubuntu下sidebar菜单展开过多，超过一页的话，出现滚动条样式，影响整体视觉效果。

**Comment by LouisGo** [comment]
@baifan 出现滚动条是正常的吧，如果忍受不了可以自定义滚动条样式或者使用第三方插件替代原生滚动条

**Comment by baifan** [comment]
@LouisGo 剛剛入門，不怎麼會調整，看了以下其他的admin樣式，是沒有出現這種情況的，出現滾動條後會佔用sidebar的寬度，整個樣式就變了，除了mac，linux和windows都有這個問題。

**Comment by baifan** [comment]
@LouisGo 
在网上搜到了解决方案。在main.less下添加了以下内容，不知道会不会出现其他问题。

```css
::-webkit-scrollbar {
    width: 0px;
    height: 1px;
}
```
